language: node_js
sudo: false
node_js:
  - "stable"
  - "iojs"
cache:
  apt: true
  directories:
    - node_modules
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      apt-get update;
      apt-get install gcc-4.9 g++-4.9;
    fi
  - BUILD_ONLY=true npm install nodegit
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
