language: node_js
node_js:
  - "stable"
  - "iojs"
cache:
  apt: true
  directories:
    - node_modules
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo apt-get build-essential
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update;
      sudo apt-get install gcc-4.8 g++-4.8;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20;
      sudo update-alternatives --config gcc;
      sudo update-alternatives --config g++;
    fi
  - BUILD_ONLY=true npm install nodegit
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
