language: node_js
node_js:
  - "stable"
  - "iojs"
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update;
      sudo apt-get install gcc-4.9 g++-4.9;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20;
      sudo update-alternatives --config gcc;
      sudo update-alternatives --config g++;
    fi
  - npm update -g
  - BUILD_ONLY=true npm install nodegit
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
